# Generated by Django 5.1 on 2024-10-01 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RAKPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='rak_media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('completed', 'Completed')], default='open', max_length=10)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('post_type', models.CharField(choices=[('offer', 'Offer'), ('request', 'Request')], max_length=10)),
                ('aura_points', models.PositiveIntegerField(default=10)),
                ('is_completed', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rak_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayItForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_points', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_rak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_it_forward_rak', to='rak.rakpost')),
                ('original_rak', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='original_rak', to='rak.rakpost')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimedRAK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_raks', to=settings.AUTH_USER_MODEL)),
                ('rak', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_rak', to='rak.rakpost')),
            ],
        ),
    ]
