# Generated by Django 5.1 on 2024-10-09 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rak', '0004_badge_rakpost_is_paid_forward_rakpost_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimaction',
            name='claimed_rak',
        ),
        migrations.RemoveField(
            model_name='rakpost',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='rakpost',
            name='user',
        ),
        migrations.CreateModel(
            name='RAKClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rak_claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='claimaction',
            name='rak_claim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='rak.rakclaim'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RandomActOfKindness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='rak_media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('completed', 'Completed')], default='open', max_length=10)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('post_type', models.CharField(choices=[('offer', 'Offer'), ('request', 'Request')], max_length=10)),
                ('aura_points', models.PositiveIntegerField(default=10)),
                ('completed_at', models.DateTimeField(null=True)),
                ('is_paid_forward', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rak_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rakclaim',
            name='rak',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rak_claim', to='rak.randomactofkindness'),
        ),
        migrations.DeleteModel(
            name='ClaimedRAK',
        ),
        migrations.DeleteModel(
            name='RAKPost',
        ),
    ]
