# Generated by Django 5.1 on 2024-10-11 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rak', '0005_remove_claimaction_claimed_rak_remove_rakpost_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayItForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_points', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_rak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_it_forward_rak', to='rak.randomactofkindness')),
                ('original_rak', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='original_rak', to='rak.randomactofkindness')),
            ],
        ),
    ]
