# Generated by Django 5.1 on 2024-10-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rak', '0008_block_report_delete_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aura_sub_level',
            field=models.CharField(default='Initiator', max_length=255),
        ),
    ]
