# Generated by Django 5.1 on 2024-10-21 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rak', '0013_randomactofkindness_rak_claims_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rakclaim',
            name='rak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='rak.randomactofkindness'),
        ),
    ]
