# Generated by Django 5.1 on 2024-10-21 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rak', '0014_alter_rakclaim_rak'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rakclaim',
            name='claimant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rak_claims', to=settings.AUTH_USER_MODEL),
        ),
    ]
