# Generated by Django 5.1 on 2024-10-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rak', '0015_alter_rakclaim_claimant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomactofkindness',
            name='rak_claims',
            field=models.ManyToManyField(null=True, related_name='raks', to='rak.rakclaim'),
        ),
    ]
