# Generated by Django 5.1 on 2024-10-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rak', '0016_alter_randomactofkindness_rak_claims'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomactofkindness',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='randomactofkindness',
            name='rak_claims',
            field=models.ManyToManyField(blank=True, related_name='raks', to='rak.rakclaim'),
        ),
    ]
