# Generated by Django 5.1 on 2024-10-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rak', '0017_alter_randomactofkindness_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomactofkindness',
            name='rak_claims',
        ),
    ]
