# Generated by Django 5.1 on 2024-10-24 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rak', '0019_rename_aura_points_randomactofkindness_aura_points_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomactofkindness',
            name='claimed_by',
        ),
        migrations.AddField(
            model_name='claimant',
            name='rak',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='rak.randomactofkindness'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='randomactofkindness',
            name='action',
            field=models.TextField(help_text='Action or price requirement needed to fulfill RAK', max_length=255),
        ),
        migrations.AlterField(
            model_name='randomactofkindness',
            name='allow_collaborators',
            field=models.BooleanField(default=False, help_text='Allow multiple claimants'),
        ),
        migrations.DeleteModel(
            name='RAKClaim',
        ),
    ]
