# Generated by Django 5.1 on 2024-10-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_block_report_userprofile_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points_from_claiming',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points_from_pay_it_forward',
            field=models.IntegerField(default=0),
        ),
    ]
