# Generated by Django 5.1 on 2024-10-02 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimedrak',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClaimAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_rak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='rak.claimedrak')),
            ],
        ),
    ]
