# Generated by Django 5.1 on 2024-10-13 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rak', '0007_userprofile_aura_color_userprofile_aura_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('inappropriate_rak', 'Inappropriate RAK'), ('inappropriate_comment', 'Inappropriate Comment'), ('unfulfilled_rak', 'Unfulfilled RAK'), ('user_block', 'User Block')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.RemoveField(
            model_name='payitforward',
            name='bonus_points',
        ),
        migrations.AddField(
            model_name='payitforward',
            name='pay_it_forward_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='randomactofkindness',
            name='allow_collaborators',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='randomactofkindness',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborative_raks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='randomactofkindness',
            name='post_anonymously',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='randomactofkindness',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payitforward',
            name='new_rak',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pay_it_forward_instance', to='rak.randomactofkindness'),
        ),
        migrations.AlterField(
            model_name='payitforward',
            name='original_rak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_it_forwards', to='rak.randomactofkindness'),
        ),
        migrations.AlterField(
            model_name='randomactofkindness',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='open', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aura_color',
            field=models.CharField(default='light yellow', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aura_level',
            field=models.CharField(default='Initiator', max_length=255),
        ),
        migrations.DeleteModel(
            name='ClaimAction',
        ),
    ]
