# Generated by Django 5.1 on 2024-10-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rak', '0009_userprofile_aura_sub_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomactofkindness',
            name='aura_points_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
