# Generated by Django 5.1 on 2024-10-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rak', '0010_randomactofkindness_aura_points_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='rakclaim',
            name='claim_anonymously',
            field=models.BooleanField(default=False),
        ),
    ]
