# Generated by Django 5.1 on 2024-10-18 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rak', '0011_rakclaim_claim_anonymously'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reported_user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
