# Generated by Django 5.1 on 2024-10-23 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rak', '0018_remove_randomactofkindness_rak_claims'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomactofkindness',
            old_name='aura_points',
            new_name='aura_points_value',
        ),
        migrations.RenameField(
            model_name='randomactofkindness',
            old_name='creator',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='randomactofkindness',
            old_name='post_type',
            new_name='rak_type',
        ),
        migrations.RemoveField(
            model_name='payitforward',
            name='pay_it_forward_by',
        ),
        migrations.RemoveField(
            model_name='randomactofkindness',
            name='aura_points_awarded',
        ),
        migrations.RemoveField(
            model_name='randomactofkindness',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='randomactofkindness',
            name='is_paid_forward',
        ),
        migrations.RemoveField(
            model_name='randomactofkindness',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='randomactofkindness',
            name='post_anonymously',
        ),
        migrations.RemoveField(
            model_name='randomactofkindness',
            name='visibility',
        ),
        migrations.AddField(
            model_name='randomactofkindness',
            name='action',
            field=models.TextField(default=1, help_text='Action or price requirement needed to fullfill rak', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='randomactofkindness',
            name='anonymous_rak',
            field=models.BooleanField(default=False, help_text='Keep created by anonymous'),
        ),
        migrations.AddField(
            model_name='randomactofkindness',
            name='private',
            field=models.BooleanField(default=False, help_text='Private is only displayed to followers'),
        ),
        migrations.AlterField(
            model_name='randomactofkindness',
            name='allow_collaborators',
            field=models.BooleanField(default=False, help_text='Optional field to allow multiple claimants'),
        ),
        migrations.AlterField(
            model_name='randomactofkindness',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='randomactofkindness',
            name='title',
            field=models.TextField(max_length=30),
        ),
        migrations.CreateModel(
            name='Claimant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Comment left by claimant', max_length=255)),
                ('anonymous_claimant', models.BooleanField(default=False, help_text='Keep Claimant anonymous')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('claimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='randomactofkindness',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rak_collaborators', to='rak.claimant'),
        ),
    ]
