# Generated by Django 5.1 on 2024-10-24 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rak', '0020_remove_randomactofkindness_claimed_by_claimant_rak_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='randomactofkindness',
            name='allow_claimants',
            field=models.BooleanField(default=False, help_text='Allow multiple claimants'),
        ),
        migrations.AlterField(
            model_name='randomactofkindness',
            name='allow_collaborators',
            field=models.BooleanField(default=False, help_text='Allow multiple collaborators '),
        ),
        migrations.CreateModel(
            name='Collaborators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Comment left by collaborator', max_length=255)),
                ('anonymous_collaborator', models.BooleanField(default=False, help_text='Keep Collaborator anonymous')),
                ('started_collabing_at', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collabs', to='rak.randomactofkindness')),
            ],
        ),
    ]
