# Generated by Django 5.1 on 2024-10-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_points_from_claiming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points_from_offers',
            field=models.IntegerField(default=0),
        ),
    ]
